### ISSUE TITLE
Wrong code

### ISSUE THREAD

**Issue by zimt28** [gwendall/meteor-impersonate#6]
There are some thing that will not work. First, `Impersonate` cannot be used, as `api.export('Impersonate');` is missing in the package.js file. When I add it, impersonating works :)

`Impersonate.undo()` will not work, as it uses the `impersonate` method on the server. This method checks for an admin user, but when you set the userId to a non-admin user before, you cannot undo it:
 `if (!Roles.userIsInRole(this.userId, ["admin"]))`. I'll see if I can find a solution. Thank you for this cool package :)

**Comment by gwendall** [comment]
Indeed, I pushed things fast yesterday and omitted a few points. I just released an update fixing those issues, let me know how it works for you.
